rm_referee:
  robot_type: drone
  send_ui_queue_delay: 0.05
  add_ui_frequency: 5
  add_ui_max_times: 10
  dbus_topic: "/dbus_data"
  interactive_data:
  ui:
    trigger_change:
      - name: "gimbal"
        config: { start_position: [ 400, 850 ], size: 15, width: 2, title: "gimbal:  " }
      - name: "shooter"
        config: { start_position: [ 400, 800 ], size: 15, width: 2, title: "shooter: " }
      - name: "target"
        config: { start_position: [ 400, 750 ], size: 15, width: 2, title: "target: " }
      - name: "camera"
        config: { start_position: [ 400, 700 ], size: 15, width: 2, title: "camera: " }
      - name: "target_view_angle"
        config: { type: "rectangle", start_position: [ 773, 554 ], end_position: [ 1060, 338 ], width: 3 }
        own_camera_name: "camera_left"
      - name: "far_target_view_angle"
        config: { type: "rectangle", start_position: [ 900, 490 ], end_position: [ 1040, 400], width: 3 }
        own_camera_name: "camera_right"
    time_change:
      - name: "drone_towards"
        config: { type: "line", width: 10 ,color: "pink", delay: 0.2 }
        data: { ori_x: 1500, ori_y: 800 }
      - name: "target_distance"
        config: { type: "float_num", start_position: [ 850, 750 ], size: 25, width: 3 ,color: "yellow", delay: 0.2 }
      - name: "target_hp"
        config: { type: "int_num", start_position: [ 850, 700 ], width: 3, size: 25, color: "yellow", delay: 0.3 }
        enemy_id: [ 1, 2, 3, 4, 5, 7 ]
    flash:
      - name: "rune_remind"
        config: { start_position: [ 880, 700 ], size: 35, width: 3,
                  color: "purple", content: "REMIND", delay: 0.5 }
    fixed:
      - name: "9m"
        config: { type: "line", width: 3, color: "yellow",
                  start_position: [ 950, 526 ], end_position: [ 970, 526 ] }
      - name: "15m"
        config: { type: "line", width: 3, color: "purple",
                  start_position: [ 950, 500 ], end_position: [ 970, 500 ] }
